'*.{ts,tsx,js}':
  - 'eslint --cache --cache-location ./node_modules/.cache/.eslintcache --fix'
  - 'prettier --loglevel warn --cache --write'
'*.{json,yml,css}': 'prettier --loglevel warn --cache --write'
